// @ts-check
const DEFAULT_API_TIMEOUT_MS = 60000;
const AGENT_RESPONSE_TIMEOUT_MS = 190000;
const AGENT_SETUP_TIMEOUT_MS = 45000;

export { AGENT_RESPONSE_TIMEOUT_MS, AGENT_SETUP_TIMEOUT_MS, DEFAULT_API_TIMEOUT_MS };
